name: Sample Python 2

on: [push]

jobs:
  build:
    runs-on: [label-1]
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install pytest
    - name: Test with pytest
      run: |
        python3 -m pytest
