name: Sample Python 2

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install python3-pip --break-system-packages
        python3 -m pip install flask --break-system-packages
        pip3 
    - name: Creating new File
      run: |
        echo "Hello" > newfile.txt
