on: push
name: deploy
jobs:
  build:
     name: Creanting New Docker Image
     runs-on: ubuntu-latest
     steps:

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       id: wait-for-push-docker-image
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and Push to Docke Hub
       uses: docker/build-push-action@v5
       with:
         #repository: ${{ repository }}
         #tag_with_ref: true
         #tag_with_sha: true
         push: true
         tags: francistv/dev-deploy
         

  deploy:
    runs-on: [self-hosted]
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Dev
      if: steps.wait-for-push-docker-image.outputs.conclusion == 'success'
      run: |
        echo "Deploying to Dev..."
        docker run -d --name dev-gninx francistv/dev-deploy:latest
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          rancistv/dev-deploy:latest

    - name: Exporting Docker Image OCI
      run: |
        sudo mkdir -p /opt/docker-image/docker-image-$(date +'%Y%m%H$S')
        docker save -o /opt/docker-image/docker-image-$(date +'%Y%m%H$S')/dev-nginx.tar francistv/dev-deploy:latest

