name: Sample Morfeus

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 
    - name: Test with pytest
      run: |
        python3 -m pytest
