on: push
name: deploy
jobs:
  build:
     name: Creanting New Docker Image
     runs-on: ubuntu-latest
     steps:

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       id: wait-for-push-docker-image
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and Push to Docke Hub
       uses: docker/build-push-action@v5
       with:
         #repository: ${{ repository }}
         #tag_with_ref: true
         #tag_with_sha: true
         push: true
         tags: francistv/dev-deploy
         

  deploy:
    name: Deploy to Dev
    runs-on: [self-hosted]
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Dev
      #if: steps.wait-for-push-docker-image.outputs.conclusion == 'success'
      run: |
        echo "Deleteing Docker imagen -> dev-nginx if exists"
        docker stop dev-gninx  || true && docker rm dev-gninx  || true
        docker rmi francistv/dev-deploy:latest
        echo "Deploying dev-nginx application to Dev..."
        docker run -d --name dev-gninx  -p 8081:80 francistv/dev-deploy:latest
        


