on: push
name: deploy
jobs:
  deploy:
     name: Creanting New Docker Image
     runs-on: ubuntu-latest
     steps:

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       id: wait-for-push-docker-image
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and Push to Docke Hub
       uses: docker/build-push-action@v5
       with:
         #repository: ${{ repository }}
         #tag_with_ref: true
         #tag_with_sha: true
         push: true
         tags: francistv/dev-deploy
  
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Test python script
      if: steps.wait-for-push-docker-image.outputs.conclusion == 'success'
      run: |
        python3 /home/docker/script.py
    - name: Creating New txt File
      run: |
         echo "Creating New File since Github Actions" > /home/docker/newfile.txt

