name: Sample Morfeus

on: [push]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-pip 
        python3 -m pip install --upgrade pip --break-system-packages
        python3 -m pip install flask --break-system-packages
        pip3 
    - name: Test python script
      run: |
        python3 /home/docker/script.py
    - name: Creating New txt File
      run: |
         echo "Creating New File since Github Actions" > newfile.txt
