on: push
name: deploy
jobs:
  deploy:
     name: Creanting New Docker Image
     runs-on: ubuntu-latest
     steps:

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and Push to Docke Hub
       uses: docker/build-push-action@v5
       with:
         #repository: ${{ repository }}
         #tag_with_ref: true
         #tag_with_sha: true
         push: true
         tags: francistv/dev-deploy

  use:
    runs-on: [self-hosted]
    steps:
      - name: Running New Docker Image on Morfeus
        run: |
          docker francistv/dev-deploy:latest
          docker image ls -a
