on: push
name: deploy
jobs:
  deploy:
     name: deploy to cluster
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@master
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:         
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: build and push to docker
       uses: docker/build-push-action@v5
       with:   
      #   username: ${{ secrets.DOCKER_USERNAME }}
      #   password: ${{ secrets.DOCKER_PASSWORD }}
         repository: ${{ github.repository }}
         tag_with_ref: true
         tag_with_sha: true
         push: true
         tags: francistv/dev-deploy:${{ github.sha }}

     - name: Deploy to Cluster
       uses: steebchen/kubectl@master
       env: 
         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
       with:
         args: set image --record deployment/my-app nginx=francistv/dev-deploy:${{ github.sha }}

     - name: verify deployment
       uses: steebchen/kubectl@master
       env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.32.3 # specify kubectl binary version explicitly
       with:
         args: '"rollout status deployment/my-app"'
       
          
